services:
  frontend:
    image: ghcr.io/bitlank/upordown-frontend:latest
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - backend

  backend:
    image: ghcr.io/bitlank/upordown-backend:latest
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_APP_USER=${DB_APP_USER}
      - DB_APP_PASSWORD=${DB_APP_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - LISTEN_PORT=3000
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  db-data:
