services:
  dev-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - dev-db-data:/var/lib/mysql

volumes:
  dev-db-data:
